"""initial schema with product units

Revision ID: 98adfdb9318b
Revises: de6d7c1c962a
Create Date: 2025-12-30 11:19:28.541503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98adfdb9318b'
down_revision = 'de6d7c1c962a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_unit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_price', sa.Float(), nullable=True))
        batch_op.alter_column('conversion_quantity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_unit', schema=None) as batch_op:
        batch_op.alter_column('conversion_quantity',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('cost_price')

    # ### end Alembic commands ###
